### ISSUE TITLE
[v5 Beta | Beta ?] QuantumENDEC fails to start due to missing dependencies

### ISSUE THREAD

**Issue by NickEASIU** [ApatheticDELL/QuantumENDEC#9] opened 2024-11-18 01:29 UTC
![Screenshot (14)](https://github.com/user-attachments/assets/b1fd22dc-44a1-4d14-ab57-0540df33eb9e)
![Screenshot (13)](https://github.com/user-attachments/assets/fe4f6eee-de30-47fb-afca-2b6048930a8d)

**Comment by NickEASIU** [comment] 2024-11-18 01:30
Tell ApatheticDELL Please.

**Comment by ApatheticDELL** [comment] 2024-11-18 14:57
We're gonna keep sounding like a broken record (if you even know what that is):
**We can't fix this issue.** Unless you provide (if you even know how to provide) additional information on your python installation/environment, we _may_ be able to guide you in the right direction.


- The issue you are experiencing is potentially an external cause, which means it's being caused by one of the dependencies that QuantumENDEC is using, not by QuantumENDEC itself.

- This could be an issue catered to a specific version of Python, so (if you even know how to figure this out) you could start by sharing your Python setup such as its version.

- This issue may be caused by user error (as in you, the user, causing the error). This could be a result of a mistake made in installing python, the dependencies of QuantumENDEC, or other.

But, we are having an extremely hard time dealing with you due to your lack of communication skills. And because of this, you are damaging your reputation up to the point where every time you'd make a new issue, we'll just end up closing it right away as soon as we see your username.

**Comment by ApatheticDELL** [comment] 2024-11-18 15:36
Already being tracked in another issue

**Closed as not planned by ApatheticDELL** 2024-11-18 15:36 UTC
Labels: duplicate, external issue
