### ISSUE TITLE
[v5 Beta | Beta 10.3] QuantumENDEC fails to start due to missing dependencies

### ISSUE THREAD

**Issue by NickEASIU** [ApatheticDELL/QuantumENDEC#4] opened 2024-11-03 16:17 UTC
![Screenshot (10)](https://github.com/user-attachments/assets/634499d8-9b01-4ab7-b36b-b4ab5e9bb81e)

**Comment by ApatheticDELL** [comment] 2024-11-05 00:20
It seems like you are experiencing an issue with the python library itself, this may not be an issue with QuantumENDEC.
You could try isolating the issue within your python installation, or re-install python completely.

**Comment by NickEASIU** [comment] 2024-11-05 17:06
`C:\Users\Nick\AppData\Local\Programs\Python\Python312\python.exe: can't open file C:\\Users\\Nick\\Downloads\\QuantumENDEC-QE5\\QuantumENDEC.py': [Errno 2] No such file or directory`
**Only the Python 3.12.5 with python.exe on it.**

**Comment by NickEASIU** [comment] 2024-11-05 17:07
So FIX it Please do it guys I appreciate it.

**Comment by BunnyTub** [comment] 2024-11-10 22:53
This is an outside issue that cannot be fixed in the code. If you can provide anything more, such as how you installed Python, Windows Store, Raw Executable, etc, it would be more helpful to help solve your problem.

**Comment by NickEASIU** [comment] 2024-11-17 16:01
**ImportError: DLL load failed while importing _cext: The specified module could not be found and Python QuantumENDEC.py Won't Start.**

**Comment by NickEASIU** [comment] 2024-11-17 16:10
### Well, did you seen this picture in VSCode? Well I can show you to see what it is:
![Screenshot (12)](https://github.com/user-attachments/assets/b293aae6-6f4e-4841-887d-77b4f2a0fdc7)
### Oh yeah That was the Problem is the kiwisolver and matplotlib. So anyways, How to fix the QuantumENDEC in Python on VSCode.

**Comment by NickEASIU** [comment] 2024-11-17 16:12
**Actually, It's QuantumENDEC-5-beta.10 This is mine.**

**Comment by meowraii** [comment] 2024-11-17 16:13
You're not telling us anything. **PROVIDE** further information regarding **YOUR** Python installation. Like did you install it via the **Microsoft Store**? **Raw executable**? We **CANNOT** **help you** if you have the **communication skills of a goldfish**.

**Comment by NickEASIU** [comment] 2024-11-17 16:31
So How to Fix QuantumENDEC tell ApatheticDell tell him!

**Comment by ApatheticDELL** [comment] 2024-11-17 17:14
CLOSED - Lack of communication skills. The issue is external (unrelated to QuantumENDEC itself).

**Closed as not planned by ApatheticDELL** 2024-11-17 17:14 UTC
Labels: duplicate, external issue
